# Generated by Django 5.2.6 on 2025-09-21 18:20

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(help_text='Brief title of the issue', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('category', models.CharField(choices=[('infrastructure', 'Infrastructure'), ('sanitation', 'Sanitation'), ('utilities', 'Utilities'), ('transport', 'Transport'), ('health', 'Health & Safety'), ('environment', 'Environment'), ('other', 'Other')], default='other', max_length=50)),
                ('location', models.CharField(help_text='Ward/Area/Address where issue is located', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('reporter_name', models.CharField(max_length=100)),
                ('reporter_email', models.EmailField(max_length=254)),
                ('reporter_phone', models.CharField(blank=True, max_length=15)),
                ('assigned_department', models.CharField(blank=True, help_text='Department responsible for this issue', max_length=100)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes for staff only')),
                ('image', models.ImageField(blank=True, null=True, upload_to='issue_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='issue_videos/')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff member assigned to handle this issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
                'ordering': ['-created_at'],
            },
        ),
    ]
