# Generated by Django 5.2.5 on 2025-09-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_record_delete_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='category',
            field=models.CharField(default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='record',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='record',
            name='priority',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='record',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
