# Generated by Django 5.2.5 on 2025-09-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_profile_email_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_category',
            field=models.CharField(choices=[('infrastructure', 'Infrastructure'), ('sanitation', 'Sanitation'), ('utility', 'Utility'), ('transport', 'Transport')], default='infrastructure', help_text='Select your admin category to see relevant issues', max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.CharField(choices=[('infrastructure', 'Infrastructure'), ('sanitation', 'Sanitation'), ('utility', 'Utility'), ('transport', 'Transport')], default='infrastructure', max_length=50),
        ),
    ]
